### PR TITLE
Ignore implicit cabal.project when using sdist build

### LINKED ISSUE #39: Do not use a cabal.project file when building from sdist
Specifying a cabal.project with sdist should be an error. cabal.project file may specify custom packages or environment that may build in a CI but may not build when a user of the sdist wants to build it.

One of the `streamly-examples` CI (https://app.circleci.com/pipelines/github/composewell/streamly-examples/93/workflows/2bb6b1e1-6f5d-4259-81a2-c1dc170a85fb/jobs/867) succeeded even though it was supposed to fail because it specified a project file which picked up a custom version of streamly.

### PR DESCRIPTION
**Pull request by harendra-kumar**
Otherwise the build might be passing in the CI and then fail in the distribution because it was depending on some custom options (e.g. a source repository package).

Fixes #39

### CODE REVIEW

File: packcheck.sh [hunk 1]
```diff
@@ -101,7 +101,7 @@ require_cmd () {
 
 # $1: command
 function run_verbose() {
-  echo "$*"
+  echo "$*" 1>&2
```
Comment (adithyaov) [inline packcheck.sh:104]: You're redirecting `stdout` to `stderr`, why?

File: packcheck.sh [hunk 2]
```diff
@@ -1013,47 +1013,97 @@ ensure_cabal() {
...
     fi
   fi
-  echo "Using cabal command [$CABALCMD]"
-}
 
-ensure_stack_yaml() {
-  if test -n "$STACK_YAML"
-  then
-    require_file $STACK_YAML
+  if test -n "$CABAL_PROJECT"
```
Comment (adithyaov) [inline packcheck.sh:1049]: I wonder if you can merge this with the upper conditional.

File: packcheck.sh [hunk 3]
```diff
@@ -1013,47 +1013,97 @@ ensure_cabal() {
...
       STACKCMD="$SDIST_STACKCMD"
-    else
+    else # sdist build
       # We run the stack command from .packcheck/<package> dir after unpacking
       # sdist
       STACKCMD="$STACKCMD --stack-yaml ../../$STACK_YAML"
     fi
   fi
+
+  if test -n "$STACK_YAML"
```
Comment (adithyaov) [inline packcheck.sh:1087]: Can this be merged with the above conditional. They seem to have a lot of similar branches.

File: packcheck.sh [hunk 4]
```diff
@@ -1277,8 +1328,46 @@ create_and_unpack_pkg_dist() {
...
   $OS_UNGZTAR_CMD $tarpath
+  echo
 
   cd ${1}
+  if test "$BUILD" = stack
+  then
+    test -e stack.yaml \
+      && echo "WARNING! Avoid including stack.yaml in a distribution" \
+      && run_verbose rm -f stack.yaml
+    $STACKCMD init
```
Comment (adithyaov) [inline packcheck.sh:1342]: Why?

PS: I haven't read the whole code. Is it required to understand the context?

File: packcheck.sh [hunk 5]
```diff
@@ -1277,8 +1328,46 @@ create_and_unpack_pkg_dist() {
...
+  else
+    # Is there a way in cabal to ignore project file?
+    # XXX how does cabal build dependencies with project files?
+    test -e cabal.project \
+      && echo "WARNING! Avoid including cabal.project in a distribution" \
+      && run_verbose rm -f cabal.project
```
Comment (adithyaov) [inline packcheck.sh:1348]: Why?

**Review by adithyaov — COMMENTED** [review]
I have not reviewed the functionality of "Ignore implicit cabal.project when using sdist build" commit properly. The rest looks good.

File: packcheck.sh (hunk 1 above)
Comment (harendra-kumar) [reply packcheck.sh:104]: This is an informative message. When we redirect the output of `run_verbose` we do not want this to be mixed with the actual output of the command.

File: packcheck.sh (hunk 2 above)
Comment (harendra-kumar) [reply packcheck.sh:1049]: Probably yes. Earlier I was adding more code here, that's why it was separate. And it was easier to think by keeping the old code intact.

File: packcheck.sh (hunk 4 above)
Comment (harendra-kumar) [reply packcheck.sh:1342]: When a build tool builds a dependency it won't take an existing stack.yaml or cabal.project into account. So our testing here would be wrong, because such a project file/stack config may have a source-repository-package for example.

File: packcheck.sh (hunk 5 above)
Comment (harendra-kumar) [reply packcheck.sh:1348]: Same as above.

File: packcheck.sh (hunk 2 above)
Comment (harendra-kumar) [reply packcheck.sh]: Merged.

File: packcheck.sh (hunk 3 above)
Comment (harendra-kumar) [reply packcheck.sh]: Merged.

File: packcheck.sh (hunk 1 above)
Comment (adithyaov) [reply packcheck.sh:104]: Ah, You're only redirecting the `echo` of the command. My bad.

**Review by adithyaov — APPROVED** [review]
Please fix up and merge.
